hibernate:
    connection:
        autocommit: false


spring:
    datasource:
        jndi-name: jdbc/Addressbook
    jpa:
        properties:
            hibernate:
                current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
                format_sql: true
#        hibernate:
#          ddl-auto: update

logging:

    file: C:\Work\Idea15\javabegin.ru\REST_AdrBook_SpringBoot_JFX\app.log

    level:
        ROOT: WARN
        org.springframework: INFO
        org.hibernate: debug
        org.hibernate.type.descriptor.sql: trace

    pattern:
        file: '%d{HH:mm:ss} %-5p [%c]  -   %m%n'
    security:
        ignored:  /**
        basic:
          enabled: false